### ISSUE TITLE
Always getting ERROR: Sonic Pi is not listening on 4557 - is it running?

### ISSUE THREAD

**Issue by yurighensev** [dermusikman/sonicpi.vim#10]
So I write a simple `play 70` buffer, execute `!sonic_pi` and then always get this error:

```
C:\WINDOWS\system32\cmd.exe /c (sonic_pi)
ERROR: Sonic Pi is not listening on 4557 - is it running?
shell returned 1
Hit any key to close this window...
```

I've checked, proccess are listening on correct ports. Tested with 4556 and 4558 as well.
Everything runs fine if I use sonic_pi GUI or open a cmd and run `sonic_pi play 70`

**Comment by dermusikman** [comment]
Sorry I hadn't seen this issue! I don't use Windows, so I don't really have a way to try duplicating your issue directly... but I'll have a look and see what I can find in the next few days

**Comment by dermusikman** [comment]
Apologies on having clearly never gotten around to this. The issue you're demonstrating is between `sonic_pi` and the Sonic Pi server itself. The server must be running in order for `sonic_pi` to work, and therefore also this plugin. That can be started manually from `[sonic-pi dir]/app/server/bin/sonic-pi-server.rb` on Linux, and I assume it's a comparable path in Windows.

As this isn't an issue with the plugin itself (and I hope you've since resolved it!), I'll close it.
