### ISSUE TITLE
License for sonicpi.vim

### ISSUE THREAD

**Issue by lilyinstarlight** [dermusikman/sonicpi.vim#22]
Hi @dermusikman!

I've been working on a fork of this sonicpi.vim plugin at https://github.com/lilyinstarlight/vim-sonic-pi. I'm wanting to start sharing my fork, but I noticed that there was no license in the original repository describing how the code can be used and modified.

Is my fork allowed and if so, are you able to license it under an open source license so that I can use it?

GitHub has a website at https://choosealicense.com/ for deciding on a license and while much of Sonic Pi is MIT licensed, I do not have a preference myself for which license you choose as long as it allows modification and distribution (which all of the licenses on that website allow).

Thank you for making sonicpi.vim and I hope you are safe and well!

**Comment by dermusikman** [comment]
Hi @lilyinstarlight!

Thank you for reaching out, and I am excited to see your fork! At a brief glance, it looks like some substantial enhancements and I look forward to exploring it!

I'm a bit embarrassed I didn't put the license in. I prefer GPLv3 and would have licensed it as such if I had thought to do so. Because you went through the trouble of forking it in the good faith it was an open license, I'll ask if you have any concerns or objections with that before updating my code to clarify it. If not, I'll try to get that updated quickly so that doesn't delay you.

Thanks, again, and I wish you health and safety, too!

**Comment by lilyinstarlight** [comment]
GPLv3 is fine with me!

I'm not sure if that would involve consensus by others who have contributed to the repository but whenever you push a license to this repo, I'll merge it to the fork and clarify the fork as GPLv3 as well.

You don't have to worry too much about delaying me either. I've just been working on the fork in little sprints here and there when I've actually had the time (and motivation). My updates still need some help to do a few things in a less dumb way anyway before I would really consider it ready for anyone else to use.

**Comment by dermusikman** [comment]
Glad to hear it - I've added the GPLv3 license to the repository. Thanks again, and good luck with the fork! I look forward to trying it out!
